/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bank.managment.system;

import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author yaraw
 */
public class Edit extends javax.swing.JFrame {
    private String cardNumber;


    /**
     * Creates new form Edit
     */
    public Edit(String cardNumber) {
    this.cardNumber = cardNumber;
        initComponents();
        
        setTitle("CLIENT'S INFORMATION - Edit");

    setLayout(null);

    ImageIcon i1 = new ImageIcon(ClassLoader.getSystemResource("icons/user.png"));
    Image i2 = i1.getImage().getScaledInstance(100, 100, Image.SCALE_DEFAULT);
    ImageIcon i3 = new ImageIcon(i2);
    JLabel label = new JLabel(i3);
    label.setBounds(40, 25, 100, 100);
    add(label);

    loadClientInfo(cardNumber);

    getContentPane().setBackground(Color.LIGHT_GRAY);

    setSize(800, 480);
    setLocation(350, 200);
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Separator = new javax.swing.JSeparator();
        lbl_ID = new javax.swing.JLabel();
        lbl_Eduction = new javax.swing.JLabel();
        lbl_Regligion = new javax.swing.JLabel();
        lbl_AccountType = new javax.swing.JLabel();
        lbl_CardNumber = new javax.swing.JLabel();
        lbl_Email = new javax.swing.JLabel();
        lbl_Occupation = new javax.swing.JLabel();
        lbl_Pin = new javax.swing.JLabel();
        lbl_Income = new javax.swing.JLabel();
        btn_BackButton = new javax.swing.JToggleButton();
        btn_Done = new javax.swing.JToggleButton();
        txt_Religion = new javax.swing.JTextField();
        txt_Account = new javax.swing.JTextField();
        txt_CardNumber = new javax.swing.JTextField();
        txt_Id = new javax.swing.JTextField();
        txt_Email = new javax.swing.JTextField();
        txt_Occupation = new javax.swing.JTextField();
        txt_Pin = new javax.swing.JTextField();
        txt_Income = new javax.swing.JTextField();
        txt_Education = new javax.swing.JTextField();
        txt_Maritalstatues = new javax.swing.JTextField();
        txt_Governorate = new javax.swing.JTextField();
        txt_Gender = new javax.swing.JTextField();
        txt_DateOfBirth = new javax.swing.JTextField();
        txt_FullName = new javax.swing.JTextField();
        txt_FatherName = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Separator.setForeground(new java.awt.Color(102, 102, 102));

        lbl_ID.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_ID.setText("ID: ");

        lbl_Eduction.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_Eduction.setText("Eduction:");

        lbl_Regligion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_Regligion.setText("Religion:");

        lbl_AccountType.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_AccountType.setText("Account Type:");

        lbl_CardNumber.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_CardNumber.setText("Card Number:");

        lbl_Email.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_Email.setText("Email:");

        lbl_Occupation.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_Occupation.setText("Occupation:");

        lbl_Pin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_Pin.setText("Pin:");

        lbl_Income.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_Income.setText("Income:");

        btn_BackButton.setBackground(new java.awt.Color(0, 0, 0));
        btn_BackButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_BackButton.setForeground(new java.awt.Color(255, 255, 255));
        btn_BackButton.setText("BACK");
        btn_BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BackButtonActionPerformed(evt);
            }
        });

        btn_Done.setBackground(new java.awt.Color(0, 0, 0));
        btn_Done.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_Done.setForeground(new java.awt.Color(255, 255, 255));
        btn_Done.setText("Done");
        btn_Done.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DoneActionPerformed(evt);
            }
        });

        txt_Religion.setBackground(new java.awt.Color(204, 204, 204));
        txt_Religion.setText("jTextField1");
        txt_Religion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ReligionActionPerformed(evt);
            }
        });

        txt_Account.setBackground(new java.awt.Color(204, 204, 204));
        txt_Account.setText("jTextField1");
        txt_Account.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_AccountActionPerformed(evt);
            }
        });

        txt_CardNumber.setBackground(new java.awt.Color(204, 204, 204));
        txt_CardNumber.setText("jTextField1");
        txt_CardNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_CardNumberActionPerformed(evt);
            }
        });

        txt_Id.setBackground(new java.awt.Color(204, 204, 204));
        txt_Id.setText("jTextField1");
        txt_Id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_IdActionPerformed(evt);
            }
        });

        txt_Email.setBackground(new java.awt.Color(204, 204, 204));
        txt_Email.setText("jTextField1");
        txt_Email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_EmailActionPerformed(evt);
            }
        });

        txt_Occupation.setBackground(new java.awt.Color(204, 204, 204));
        txt_Occupation.setText("jTextField1");
        txt_Occupation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_OccupationActionPerformed(evt);
            }
        });

        txt_Pin.setBackground(new java.awt.Color(204, 204, 204));
        txt_Pin.setText("jTextField1");
        txt_Pin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_PinActionPerformed(evt);
            }
        });

        txt_Income.setBackground(new java.awt.Color(204, 204, 204));
        txt_Income.setText("jTextField1");
        txt_Income.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_IncomeActionPerformed(evt);
            }
        });

        txt_Education.setBackground(new java.awt.Color(204, 204, 204));
        txt_Education.setText("jTextField1");
        txt_Education.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_EducationActionPerformed(evt);
            }
        });

        txt_Maritalstatues.setBackground(new java.awt.Color(204, 204, 204));
        txt_Maritalstatues.setText("jTextField1");

        txt_Governorate.setBackground(new java.awt.Color(204, 204, 204));
        txt_Governorate.setText("jTextField1");
        txt_Governorate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_GovernorateActionPerformed(evt);
            }
        });

        txt_Gender.setBackground(new java.awt.Color(204, 204, 204));
        txt_Gender.setText("jTextField1");

        txt_DateOfBirth.setBackground(new java.awt.Color(204, 204, 204));
        txt_DateOfBirth.setText("jTextField1");

        txt_FullName.setBackground(new java.awt.Color(204, 204, 204));
        txt_FullName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txt_FullName.setText("Yara");
        txt_FullName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_FullNameActionPerformed(evt);
            }
        });

        txt_FatherName.setBackground(new java.awt.Color(204, 204, 204));
        txt_FatherName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txt_FatherName.setText("Mohammed");
        txt_FatherName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_FatherNameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txt_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(Separator, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txt_FullName, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_FatherName, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_DateOfBirth, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                                    .addComponent(txt_Gender))
                                .addGap(351, 351, 351)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_Maritalstatues, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_Governorate, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txt_Id, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_Regligion, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txt_Religion, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_AccountType, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txt_Account, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_CardNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txt_CardNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(94, 94, 94)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_Income, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lbl_Pin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbl_Eduction, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbl_Occupation, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_Occupation)
                            .addComponent(txt_Pin)
                            .addComponent(txt_Income)
                            .addComponent(txt_Education))))
                .addGap(199, 199, 199))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_Done, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(208, 208, 208))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_FatherName, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(txt_FullName, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_Governorate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_DateOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_Maritalstatues, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(Separator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_ID)
                    .addComponent(lbl_Eduction)
                    .addComponent(txt_Id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Education, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Regligion)
                    .addComponent(lbl_Occupation, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Religion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Occupation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_AccountType)
                    .addComponent(lbl_Pin, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Account, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Pin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_CardNumber)
                    .addComponent(lbl_Income)
                    .addComponent(txt_CardNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Income, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Email)
                    .addComponent(txt_Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Done, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(114, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BackButtonActionPerformed
        new Info(cardNumber).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_BackButtonActionPerformed

    private void btn_DoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DoneActionPerformed
                                           
    try {

        
        String fullName = txt_FullName.getText();
        String dob = txt_DateOfBirth.getText();
        String gender = txt_Gender.getText();
        String governorate = txt_Governorate.getText();
        String marital = txt_Maritalstatues.getText();
        String education = txt_Education.getText();
        String nationalID = txt_Id.getText();
        String income = txt_Income.getText();
        String religion = txt_Religion.getText();
        String occupation = txt_Occupation.getText();
        String email = txt_Email.getText();
        String card = txt_CardNumber.getText();
        String pin = txt_Pin.getText();
        String fatherName = txt_FatherName.getText();

        
        if (fullName.isEmpty() || dob.isEmpty() || gender.isEmpty() || governorate.isEmpty() ||
            marital.isEmpty() || education.isEmpty() || nationalID.isEmpty() || income.isEmpty() ||
            religion.isEmpty() || occupation.isEmpty() || email.isEmpty() || card.isEmpty() || pin.isEmpty() || fatherName.isEmpty()) {

            JOptionPane.showMessageDialog(this, "Please fill all fields!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Conn c = new Conn();

        
        String q1 = "SELECT customer_id FROM users WHERE card=?";
        java.sql.PreparedStatement pst1 = c.c.prepareStatement(q1);
        pst1.setString(1, card);

        java.sql.ResultSet rs = pst1.executeQuery();
        
        if (!rs.next()) {
            JOptionPane.showMessageDialog(this, "Card Number not found!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int customerID = rs.getInt("customer_id");

        // 4) UPDATE customers
        String updateCustomer = "UPDATE customers SET full_name=?, father_name=?, date_of_birth=?, gender=?, governorate=?, marital_status=?, education=?, national_id=?, income=?, religion=?, occupation=?, email=? WHERE id=?";
        java.sql.PreparedStatement pst2 = c.c.prepareStatement(updateCustomer);

        pst2.setString(1, fullName);
        pst2.setString(2, fatherName);
        pst2.setString(3, dob);
        pst2.setString(4, gender);
        pst2.setString(5, governorate);
        pst2.setString(6, marital);
        pst2.setString(7, education);
        pst2.setString(8, nationalID);
        pst2.setString(9, income);
        pst2.setString(10, religion);
        pst2.setString(11, occupation);
        pst2.setString(12, email);
        pst2.setInt(13, customerID);

        pst2.executeUpdate();

        
        String updateUser = "UPDATE users SET pin=? WHERE card=?";
        java.sql.PreparedStatement pst3 = c.c.prepareStatement(updateUser);
        pst3.setString(1, pin);
        pst3.setString(2, card);
        pst3.executeUpdate();

        JOptionPane.showMessageDialog(this, "Updated Successfully!");

    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        ex.printStackTrace();
    }




    }//GEN-LAST:event_btn_DoneActionPerformed

    private void txt_ReligionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ReligionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ReligionActionPerformed

    private void txt_AccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_AccountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_AccountActionPerformed

    private void txt_CardNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_CardNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_CardNumberActionPerformed

    private void txt_IdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_IdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_IdActionPerformed

    private void txt_EmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_EmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_EmailActionPerformed

    private void txt_OccupationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_OccupationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_OccupationActionPerformed

    private void txt_PinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_PinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_PinActionPerformed

    private void txt_IncomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_IncomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_IncomeActionPerformed

    private void txt_EducationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_EducationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_EducationActionPerformed

    private void txt_GovernorateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_GovernorateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_GovernorateActionPerformed

    private void txt_FullNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_FullNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_FullNameActionPerformed

    private void txt_FatherNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_FatherNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_FatherNameActionPerformed
private void loadClientInfo(String cardNumber){
    try {
        Conn c = new Conn();
        String query = "SELECT cu.*, u.card, u.pin, u.balance " +
                       "FROM customers cu " +
                       "JOIN users u ON cu.id = u.customer_id " +
                       "WHERE u.card=?";

        java.sql.PreparedStatement pst = c.c.prepareStatement(query);
        pst.setString(1, cardNumber);

        java.sql.ResultSet rs = pst.executeQuery();

        if(rs.next()){
            
            txt_FullName.setText(rs.getString("full_name"));
            txt_FatherName.setText(rs.getString("father_name"));
            txt_DateOfBirth.setText(rs.getString("date_of_birth"));
            txt_Gender.setText(rs.getString("gender"));
            txt_Maritalstatues.setText(rs.getString("marital_status"));
            txt_Id.setText(rs.getString("national_id"));
            txt_Religion.setText(rs.getString("religion"));
            txt_Education.setText(rs.getString("education"));
            txt_Occupation.setText(rs.getString("occupation"));
            txt_Income.setText(rs.getString("income"));
            txt_Email.setText(rs.getString("email"));
            txt_Account.setText(rs.getString("account_type"));
            txt_Governorate.setText(rs.getString("governorate"));

            
            txt_CardNumber.setText(rs.getString("card"));
            txt_Pin.setText(rs.getString("pin"));
        }

    } catch(Exception e){
        e.printStackTrace();
    }


}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        String cardNumber = "5664-1370-6686-5"; 
    java.awt.EventQueue.invokeLater(() -> {
        new Edit(cardNumber).setVisible(true);
    });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator Separator;
    private javax.swing.JToggleButton btn_BackButton;
    private javax.swing.JToggleButton btn_Done;
    private javax.swing.JLabel lbl_AccountType;
    private javax.swing.JLabel lbl_CardNumber;
    private javax.swing.JLabel lbl_Eduction;
    private javax.swing.JLabel lbl_Email;
    private javax.swing.JLabel lbl_ID;
    private javax.swing.JLabel lbl_Income;
    private javax.swing.JLabel lbl_Occupation;
    private javax.swing.JLabel lbl_Pin;
    private javax.swing.JLabel lbl_Regligion;
    private javax.swing.JTextField txt_Account;
    private javax.swing.JTextField txt_CardNumber;
    private javax.swing.JTextField txt_DateOfBirth;
    private javax.swing.JTextField txt_Education;
    private javax.swing.JTextField txt_Email;
    private javax.swing.JTextField txt_FatherName;
    private javax.swing.JTextField txt_FullName;
    private javax.swing.JTextField txt_Gender;
    private javax.swing.JTextField txt_Governorate;
    private javax.swing.JTextField txt_Id;
    private javax.swing.JTextField txt_Income;
    private javax.swing.JTextField txt_Maritalstatues;
    private javax.swing.JTextField txt_Occupation;
    private javax.swing.JTextField txt_Pin;
    private javax.swing.JTextField txt_Religion;
    // End of variables declaration//GEN-END:variables
}
