package bank.managment.system;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author haidy
 */

import bank.managment.system.Deposit;
import java.awt.Color;
import javax.swing.JOptionPane;
import java.util.Random;
import javax.swing.ImageIcon;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JFrame;
import javax.swing.JLabel;
public class SignUpPage3 extends JFrame implements ActionListener {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SignUpPage3.class.getName());
    private String formNO;
    private String pin;
    private String cardNumber;

    
    public void setFormNo(String formNO){
    this.formNO = formNO;
    
    lblFormNo.setText("Form No: " + formNO);
}

    public void setPIN(String pin){
        this.pin = pin;
    }
    
    
      
    public SignUpPage3(String cardNumber) {
    this.cardNumber = cardNumber;
        initComponents();
                setTitle("NEW ACCOUNT APPLICATION FORM - PAGE 3");
                
                

        
        this.setSize(850, 800);
        setLocation(350, 200);
        getContentPane().setBackground(Color.WHITE);
        
         ImageIcon i1 = new ImageIcon(ClassLoader.getSystemResource("icons/logo.jpg"));
        Image i2 =i1.getImage().getScaledInstance(100, 100, Image.SCALE_DEFAULT);
        ImageIcon i3 = new ImageIcon(i2);
        JLabel label = new JLabel(i3);
        label.setBounds(120, 5, 150,150);
        add(label);
        
    this.setResizable(false);
    this.setLocationRelativeTo(null);   
try {
  
} catch (Exception e) {
    System.out.println("Error loading icon: " + e.getMessage());
}
                 setLocationRelativeTo(null);
                 btngAccountType.add(SavingAccount);
                 btngAccountType.add(FixedDepositAccount);
                 btngAccountType.add(CurrentAccount);
                 btngAccountType.add(RecurringDepositAccount);
                 
                 
                                 btnSubmit.addActionListener(this);
                                 btnCancel.addActionListener(this);



    }
    public SignUpPage3(){
        this(null);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngAccountType = new javax.swing.ButtonGroup();
        lblFormNo = new javax.swing.JLabel();
        lblAccountType = new javax.swing.JLabel();
        FixedDepositAccount = new javax.swing.JRadioButton();
        SavingAccount = new javax.swing.JRadioButton();
        RecurringDepositAccount = new javax.swing.JRadioButton();
        CurrentAccount = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblPin = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblServicesRequired = new javax.swing.JLabel();
        ATM_Card = new javax.swing.JCheckBox();
        ChequeBook = new javax.swing.JCheckBox();
        MobileBanking = new javax.swing.JCheckBox();
        EmailAlerts = new javax.swing.JCheckBox();
        E_Statement = new javax.swing.JCheckBox();
        InternetBanking = new javax.swing.JCheckBox();
        btnCancel = new javax.swing.JButton();
        btnSubmit = new javax.swing.JButton();
        lblPage3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblFormNo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblFormNo.setText("Form No: 6211");

        lblAccountType.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblAccountType.setText("Account Type:");

        FixedDepositAccount.setBackground(new java.awt.Color(255, 255, 255));
        btngAccountType.add(FixedDepositAccount);
        FixedDepositAccount.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        FixedDepositAccount.setText("Fixed Deposit Account");
        FixedDepositAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FixedDepositAccountActionPerformed(evt);
            }
        });

        SavingAccount.setBackground(new java.awt.Color(255, 255, 255));
        btngAccountType.add(SavingAccount);
        SavingAccount.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        SavingAccount.setText("Saving Account");
        SavingAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SavingAccountActionPerformed(evt);
            }
        });

        RecurringDepositAccount.setBackground(new java.awt.Color(255, 255, 255));
        btngAccountType.add(RecurringDepositAccount);
        RecurringDepositAccount.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        RecurringDepositAccount.setText("Recurring Deposit Account");
        RecurringDepositAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RecurringDepositAccountActionPerformed(evt);
            }
        });

        CurrentAccount.setBackground(new java.awt.Color(255, 255, 255));
        btngAccountType.add(CurrentAccount);
        CurrentAccount.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CurrentAccount.setText("Current Account");
        CurrentAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CurrentAccountActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel6.setText("Card Number:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("(The 16-digit Card number)");

        lblPin.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblPin.setText("PIN:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("(4-digit number)");

        lblServicesRequired.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblServicesRequired.setText("Services Required:");

        ATM_Card.setBackground(new java.awt.Color(255, 255, 255));
        ATM_Card.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ATM_Card.setText("ATM Card");

        ChequeBook.setBackground(new java.awt.Color(255, 255, 255));
        ChequeBook.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ChequeBook.setText("Cheque Book");
        ChequeBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChequeBookActionPerformed(evt);
            }
        });

        MobileBanking.setBackground(new java.awt.Color(255, 255, 255));
        MobileBanking.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        MobileBanking.setText("Mobile Banking");

        EmailAlerts.setBackground(new java.awt.Color(255, 255, 255));
        EmailAlerts.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        EmailAlerts.setText("Email Alerts");
        EmailAlerts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailAlertsActionPerformed(evt);
            }
        });

        E_Statement.setBackground(new java.awt.Color(255, 255, 255));
        E_Statement.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        E_Statement.setText("E-Statement");
        E_Statement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E_StatementActionPerformed(evt);
            }
        });

        InternetBanking.setBackground(new java.awt.Color(255, 255, 255));
        InternetBanking.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        InternetBanking.setText("Internet Banking");
        InternetBanking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InternetBankingActionPerformed(evt);
            }
        });

        btnCancel.setBackground(new java.awt.Color(0, 0, 0));
        btnCancel.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnSubmit.setBackground(new java.awt.Color(0, 0, 0));
        btnSubmit.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnSubmit.setForeground(new java.awt.Color(255, 255, 255));
        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        lblPage3.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        lblPage3.setText("Page 3: Account Detalis");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("XXXX");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("XXXX-XXXX-XXXX-4581");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(676, 676, 676)
                        .addComponent(lblFormNo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(261, 261, 261)
                        .addComponent(lblPage3)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap(1562, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAccountType)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(189, 189, 189)
                                .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblServicesRequired)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(SavingAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CurrentAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addGap(224, 224, 224)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(RecurringDepositAccount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(FixedDepositAccount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(ATM_Card, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(EmailAlerts, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                                    .addComponent(ChequeBook, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblPin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(215, 215, 215)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(MobileBanking, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(InternetBanking)
                                            .addComponent(E_Statement)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(218, 218, 218)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(1318, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(lblAccountType))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblFormNo)
                        .addGap(24, 24, 24)
                        .addComponent(lblPage3)))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CurrentAccount)
                    .addComponent(RecurringDepositAccount))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SavingAccount)
                    .addComponent(FixedDepositAccount))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel9))
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPin)
                    .addComponent(jLabel4))
                .addGap(20, 20, 20)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(lblServicesRequired)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ATM_Card, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InternetBanking))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ChequeBook)
                    .addComponent(MobileBanking))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(E_Statement)
                    .addComponent(EmailAlerts))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SavingAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SavingAccountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SavingAccountActionPerformed

    private void FixedDepositAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FixedDepositAccountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FixedDepositAccountActionPerformed

    private void CurrentAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CurrentAccountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CurrentAccountActionPerformed

    private void RecurringDepositAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RecurringDepositAccountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RecurringDepositAccountActionPerformed

    private void ChequeBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChequeBookActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ChequeBookActionPerformed

    private void EmailAlertsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailAlertsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailAlertsActionPerformed

    private void E_StatementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E_StatementActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_E_StatementActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed

    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        
    }//GEN-LAST:event_btnCancelActionPerformed

    private void InternetBankingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InternetBankingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InternetBankingActionPerformed

  @Override
public void actionPerformed(ActionEvent ae) {
    try {
        if (ae.getSource() == btnSubmit) {

           
            String accountType = null;
            if (SavingAccount.isSelected()) accountType = "Saving Account";
            else if (CurrentAccount.isSelected()) accountType = "Current Account";
            else if (FixedDepositAccount.isSelected()) accountType = "Fixed Deposit Account";
            else if (RecurringDepositAccount.isSelected()) accountType = "Recurring Deposit Account";

            if (accountType == null) {
                JOptionPane.showMessageDialog(this, "Please select an Account Type.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            
            Random rand = new Random();
            String cardNumber = String.format("%04d-%04d-%04d-%04d",
                    rand.nextInt(10000), rand.nextInt(10000),
                    rand.nextInt(10000), rand.nextInt(10000));

            

            Conn c = new Conn();

            
            String updateCustomer = "UPDATE customers SET account_type='"+accountType+"' WHERE form_no='"+formNO+"'";
            c.s.executeUpdate(updateCustomer);

           
            boolean atm = ATM_Card.isSelected();
            boolean cheque = ChequeBook.isSelected();
            boolean mobile = MobileBanking.isSelected();
            boolean email = EmailAlerts.isSelected();
            boolean estatement = E_Statement.isSelected();
            boolean internet = InternetBanking.isSelected();

            int customerId = 0;
            var rs = c.s.executeQuery("SELECT id FROM customers WHERE form_no='"+formNO+"'");
            if (rs.next()) customerId = rs.getInt("id");

            if(atm) c.s.executeUpdate("INSERT INTO requested_services(customer_id, service_name, is_selected) VALUES("+customerId+",'ATM CARD',1)");
            if(cheque) c.s.executeUpdate("INSERT INTO requested_services(customer_id, service_name, is_selected) VALUES("+customerId+",'Cheque Book',1)");
            if(mobile) c.s.executeUpdate("INSERT INTO requested_services(customer_id, service_name, is_selected) VALUES("+customerId+",'Mobile Banking',1)");
            if(email) c.s.executeUpdate("INSERT INTO requested_services(customer_id, service_name, is_selected) VALUES("+customerId+",'EMAIL Alerts',1)");
            if(estatement) c.s.executeUpdate("INSERT INTO requested_services(customer_id, service_name, is_selected) VALUES("+customerId+",'E_Statement',1)");
            if(internet) c.s.executeUpdate("INSERT INTO requested_services(customer_id, service_name, is_selected) VALUES("+customerId+",'Internet Banking',1)");

            
            var rsCheck = c.s.executeQuery("SELECT * FROM users WHERE customer_id="+customerId);
            if(rsCheck.next()){
                
                c.s.executeUpdate("UPDATE users SET card='"+cardNumber+"', pin='"+pin+"' WHERE customer_id="+customerId);
            } else {
                
                c.s.executeUpdate("INSERT INTO users(customer_id, card, pin, balance) VALUES("+customerId+",'"+cardNumber+"','"+pin+"',0)");
            }

            
            JOptionPane.showMessageDialog(this, "Account created successfully!\nCard Number: "+cardNumber+"\nPIN: "+pin);

            
            this.cardNumber = cardNumber;
            this.dispose();
            new Deposit(this.cardNumber).setVisible(true);

        } else if (ae.getSource() == btnCancel) {
            this.dispose();
            new Login().setVisible(true);
        }

    } catch(Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }

}




 

public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SignUpPage3().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox ATM_Card;
    private javax.swing.JCheckBox ChequeBook;
    private javax.swing.JRadioButton CurrentAccount;
    private javax.swing.JCheckBox E_Statement;
    private javax.swing.JCheckBox EmailAlerts;
    private javax.swing.JRadioButton FixedDepositAccount;
    private javax.swing.JCheckBox InternetBanking;
    private javax.swing.JCheckBox MobileBanking;
    private javax.swing.JRadioButton RecurringDepositAccount;
    private javax.swing.JRadioButton SavingAccount;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSubmit;
    private javax.swing.ButtonGroup btngAccountType;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblAccountType;
    private javax.swing.JLabel lblFormNo;
    private javax.swing.JLabel lblPage3;
    private javax.swing.JLabel lblPin;
    private javax.swing.JLabel lblServicesRequired;
    // End of variables declaration//GEN-END:variables
}
