package bank.managment.system;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import java.util.*;
import javax.swing.JLabel;
import javax.swing.*;
import javax.swing.JTextField;
import java.awt.event.*;

public class SignUpPage2 extends JFrame implements ActionListener {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SignUpPage2.class.getName());
    private String formNO;
    private String pin;


    
    public void setFormNo(String formNO){
    this.formNO = formNO;
    lblFormNo.setText("Form No: " + formNO);
}

    public void setPIN(String Pin){
        this.pin = Pin;
    }
    
    /**
     * Creates new form signUpPage2
     */
    public SignUpPage2() {
        initComponents();
        setTitle("NEW ACCOUNT APPLICATION FORM - PAGE 2");
        
        
        
        
        
        
        
         ImageIcon i1 = new ImageIcon(ClassLoader.getSystemResource("icons/logo.jpg"));
        Image i2 =i1.getImage().getScaledInstance(100, 100, Image.SCALE_DEFAULT);
        ImageIcon i3 = new ImageIcon(i2);
        JLabel label = new JLabel(i3);
        label.setBounds(120, 5, 150,150);
        add(label);
        
        this.setSize(850, 800);
        setLocation(350, 200);
        getContentPane().setBackground(Color.WHITE);
        
    this.setResizable(false);
    this.setLocationRelativeTo(null); 
        try {
   
} catch (Exception e) {
    System.out.println("Error loading icon: " + e.getMessage());
}
               
         setLocationRelativeTo(null);
         
               txtIDno.setText("");

               
               cbReligion.removeAllItems();
             
               cbReligion.addItem("Select religion");
               
               cbReligion.addItem("muslim");
               cbReligion.addItem("christian");
               cbReligion.addItem("sikh");
               cbReligion.addItem("others");
               
                 cbIncom.removeAllItems();
                  cbIncom.addItem("Select income range");
                 cbIncom.addItem("No Income");
                 cbIncom.addItem("Less than 5,000");
                 cbIncom.addItem("5,000 - 10,000");
                 cbIncom.addItem("10,001 - 20,000");
                 cbIncom.addItem("More than 20,000");
                 
               cbEductionalQualification.removeAllItems();
                cbEductionalQualification.addItem("Select education");
                cbEductionalQualification.addItem("Non-Graduate");
                 cbEductionalQualification.addItem("Graduate");
                  cbEductionalQualification.addItem("Doctorate");
                  cbEductionalQualification.addItem("Post-Graduate");
                    cbEductionalQualification.addItem("Others");
                    cbOccupation.removeAllItems();
                     cbOccupation.addItem("Select occupation");
                          cbOccupation.addItem("Student");
                     cbOccupation.addItem("Salaried");
                  cbOccupation.addItem("Self-Employed");
                  cbOccupation.addItem("Business");
                  cbOccupation.addItem("Retired");
                   cbOccupation.addItem("Others");

                 
                 
                       
                 btnNextToPage3.addActionListener(this);
                   
               
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        lblPage2 = new javax.swing.JLabel();
        lblFormNo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbReligion = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        cbIncom = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        cbEductionalQualification = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        cbOccupation = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        txtIDno = new javax.swing.JTextField();
        btnNextToPage3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblPage2.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        lblPage2.setText("Page 2 : Additional Details");

        lblFormNo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblFormNo.setText("From No: 6211");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Regligion:");

        cbReligion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbReligion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbReligionActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Income:");

        cbIncom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Null", "<5,000", "5,000 - 10,000", "10,001 - 20,000", "Above 10,000" }));
        cbIncom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbIncomActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Eductional Qualification:");

        cbEductionalQualification.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbEductionalQualification.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbEductionalQualificationActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Occupation:");

        cbOccupation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbOccupation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbOccupationActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("ID Number:");

        txtIDno.setText("jTextField1");
        txtIDno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDnoActionPerformed(evt);
            }
        });

        btnNextToPage3.setBackground(new java.awt.Color(0, 0, 0));
        btnNextToPage3.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnNextToPage3.setForeground(new java.awt.Color(255, 255, 255));
        btnNextToPage3.setText("Next");
        btnNextToPage3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextToPage3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(261, 261, 261)
                .addComponent(lblPage2)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 682, Short.MAX_VALUE)
                .addComponent(lblFormNo)
                .addGap(257, 257, 257))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnNextToPage3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(45, 45, 45)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbOccupation, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtIDno)
                                    .addComponent(cbEductionalQualification, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbIncom, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(170, 170, 170)
                                .addComponent(cbReligion, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(185, 185, 185))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblFormNo)
                .addGap(21, 21, 21)
                .addComponent(lblPage2)
                .addGap(118, 118, 118)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbReligion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbIncom, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbEductionalQualification, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cbOccupation, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIDno, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(88, 88, 88)
                .addComponent(btnNextToPage3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(237, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbReligionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbReligionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbReligionActionPerformed

    private void btnNextToPage3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextToPage3ActionPerformed

    }//GEN-LAST:event_btnNextToPage3ActionPerformed

    private void txtIDnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDnoActionPerformed

    private void cbIncomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbIncomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbIncomActionPerformed

    private void cbEductionalQualificationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEductionalQualificationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbEductionalQualificationActionPerformed

    private void cbOccupationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbOccupationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbOccupationActionPerformed
      
    
     
    public void actionPerformed(ActionEvent ae) {
        
        
        
    
    String religion = (String) cbReligion.getSelectedItem();
    String income = (String) cbIncom.getSelectedItem();
    String education = (String) cbEductionalQualification.getSelectedItem();
    String occupation = (String) cbOccupation.getSelectedItem();
    String nationalId = txtIDno.getText(); 
    

    try {
        
        

if (religion.equals("Select religion") || income.equals("Select income range") || 
    education.equals("Select education") || occupation.equals("Select occupation") || nationalId.isEmpty()) {
    JOptionPane.showMessageDialog(this, "Please fill all required fields!", "Error", JOptionPane.ERROR_MESSAGE);
    return;
}


        Conn c = new Conn();
        
        String query = "UPDATE customers SET religion='" + religion + 
               "', income='" + income + 
               "', education='" + education + 
               "', occupation='" + occupation + 
               "', national_id='" + nationalId + 
               "' WHERE form_no='" + formNO + "'";

        c.s.executeUpdate(query);

        

        SignUpPage3 nextPage = new SignUpPage3();
        nextPage.setFormNo(formNO);
        nextPage.setPIN(pin);
        nextPage.setVisible(true);
        this.dispose();

    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
}
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SignUpPage2().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNextToPage3;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cbEductionalQualification;
    private javax.swing.JComboBox<String> cbIncom;
    private javax.swing.JComboBox<String> cbOccupation;
    private javax.swing.JComboBox<String> cbReligion;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lblFormNo;
    private javax.swing.JLabel lblPage2;
    private javax.swing.JTextField txtIDno;
    // End of variables declaration//GEN-END:variables
}



