package bank.managment.system;


import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import java.util.*;
import com.toedter.calendar.JDayChooser;
import javax.swing.JLabel;
import javax.swing.*;
import javax.swing.JTextField;
import java.awt.event.*;



/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author haidy
 */ 
  public class SignUpPage1 extends JFrame implements ActionListener {
      long random;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SignUpPage1.class.getName());
   
    /**
     * Creates new form SignUpPage1
     */
    public SignUpPage1() {
        initComponents();
        setTitle("NEW ACCOUNT APPLICATION FORM");
        
        Random ran = new Random();
        random = Math.abs((ran.nextLong()% 9000L) + 1000L);
        lblApplicationFormNo.setText("APPLICATION FORM NO." + random);
        
        
        btnNextToPage2.addActionListener(this);
        
        
        
        
        ImageIcon i1 = new ImageIcon(ClassLoader.getSystemResource("icons/logo.jpg"));
        Image i2 =i1.getImage().getScaledInstance(100, 100, Image.SCALE_DEFAULT);
        ImageIcon i3 = new ImageIcon(i2);
        JLabel label = new JLabel(i3);
        label.setBounds(70, 10, 100,100);
        add(label);
        
        this.setSize(850, 800);
        setLocation(350, 200);
        getContentPane().setBackground(Color.WHITE);
        
    this.setResizable(false);
     this.setLocationRelativeTo(null); 
           try {
    
} catch (Exception e) {
    System.out.println("Error loading icon: " + e.getMessage());
}
               
        setLocationRelativeTo(null);
        txtName.setText("");
        txtFatherName.setText("");
        txtEmail.setText("");  
        
                txtPin.setText("");
        txtGovernorate.setText("");
        gbtnGender.add(ckbMale);
        gbtnGender.add(ckbFemale);
gbtnMaritalStatues.add(ckbMarried);
gbtnMaritalStatues.add(ckbUnmarried);
gbtnMaritalStatues.add(ckbOther);


 

    }
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gbtnGender = new javax.swing.ButtonGroup();
        gbtnMaritalStatues = new javax.swing.ButtonGroup();
        lblApplicationFormNo = new javax.swing.JLabel();
        lblPage1Personaldetails = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblFatherName = new javax.swing.JLabel();
        txtFatherName = new javax.swing.JTextField();
        ckbMale = new javax.swing.JRadioButton();
        ckbFemale = new javax.swing.JRadioButton();
        lblGender = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblMaritalStatues = new javax.swing.JLabel();
        ckbMarried = new javax.swing.JRadioButton();
        ckbOther = new javax.swing.JRadioButton();
        txtPin = new javax.swing.JTextField();
        lblPin = new javax.swing.JLabel();
        lblGavernorate = new javax.swing.JLabel();
        txtGovernorate = new javax.swing.JTextField();
        btnNextToPage2 = new javax.swing.JButton();
        space = new javax.swing.JPanel();
        lblDateOfBirth = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        ckbUnmarried = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("APPLICATION FORM NO.6211\n");

        lblApplicationFormNo.setFont(new java.awt.Font("Segoe UI", 1, 38)); // NOI18N
        lblApplicationFormNo.setText("APPLICATION FORM NO.1687");

        lblPage1Personaldetails.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        lblPage1Personaldetails.setText("Page 1 : Personal details");

        lblName.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblName.setText("Name:");

        txtName.setText("enter name");
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        lblFatherName.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblFatherName.setText("Father's Name:");

        txtFatherName.setText("enter father's name");
        txtFatherName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFatherNameActionPerformed(evt);
            }
        });

        gbtnGender.add(ckbMale);
        ckbMale.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ckbMale.setForeground(new java.awt.Color(51, 51, 51));
        ckbMale.setText("Male");

        gbtnGender.add(ckbFemale);
        ckbFemale.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ckbFemale.setForeground(new java.awt.Color(51, 51, 51));
        ckbFemale.setText("Female");
        ckbFemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbFemaleActionPerformed(evt);
            }
        });

        lblGender.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblGender.setText("Gender:");

        lblEmail.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblEmail.setText("Email Adrress:");

        txtEmail.setText("enter email");

        lblMaritalStatues.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblMaritalStatues.setText("Marital statues:");

        gbtnMaritalStatues.add(ckbMarried);
        ckbMarried.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ckbMarried.setText("Married");
        ckbMarried.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbMarriedActionPerformed(evt);
            }
        });

        gbtnMaritalStatues.add(ckbOther);
        ckbOther.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ckbOther.setText("Other");
        ckbOther.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbOtherActionPerformed(evt);
            }
        });

        txtPin.setText("enter code");
        txtPin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPinActionPerformed(evt);
            }
        });

        lblPin.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblPin.setText("Pin Code:");

        lblGavernorate.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblGavernorate.setText("Governorate:");

        txtGovernorate.setText("enter state");
        txtGovernorate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGovernorateActionPerformed(evt);
            }
        });

        btnNextToPage2.setBackground(new java.awt.Color(0, 0, 0));
        btnNextToPage2.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnNextToPage2.setForeground(new java.awt.Color(255, 255, 255));
        btnNextToPage2.setText("Next");
        btnNextToPage2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextToPage2ActionPerformed(evt);
            }
        });

        space.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout spaceLayout = new javax.swing.GroupLayout(space);
        space.setLayout(spaceLayout);
        spaceLayout.setHorizontalGroup(
            spaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        spaceLayout.setVerticalGroup(
            spaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 63, Short.MAX_VALUE)
        );

        lblDateOfBirth.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblDateOfBirth.setText("Date of Birth:");

        gbtnMaritalStatues.add(ckbUnmarried);
        ckbUnmarried.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ckbUnmarried.setText("Unmarried");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(372, 372, 372)
                .addComponent(space, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(71, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblMaritalStatues)
                                .addGap(71, 71, 71)
                                .addComponent(ckbMarried)
                                .addGap(103, 103, 103)
                                .addComponent(ckbUnmarried, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(87, 87, 87)
                                .addComponent(ckbOther))
                            .addComponent(lblDateOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addComponent(lblApplicationFormNo))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(209, 209, 209)
                                .addComponent(lblPage1Personaldetails, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lblFatherName, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                                    .addComponent(lblGender, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(71, 71, 71)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(ckbMale, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(104, 104, 104)
                                        .addComponent(ckbFemale, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtFatherName)
                                    .addComponent(txtName, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
                                    .addComponent(txtEmail)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnNextToPage2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(lblPin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblGavernorate, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE))
                                    .addGap(71, 71, 71)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtPin, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtGovernorate, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(69, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lblApplicationFormNo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPage1Personaldetails)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(space, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFatherName)
                    .addComponent(txtFatherName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblDateOfBirth, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGender, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ckbMale, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ckbFemale, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMaritalStatues, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ckbMarried, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ckbOther, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ckbUnmarried, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPin)
                    .addComponent(txtPin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGavernorate)
                    .addComponent(txtGovernorate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addComponent(btnNextToPage2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPinActionPerformed

    private void txtGovernorateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGovernorateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGovernorateActionPerformed

    private void ckbMarriedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbMarriedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckbMarriedActionPerformed

    private void btnNextToPage2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextToPage2ActionPerformed

    }//GEN-LAST:event_btnNextToPage2ActionPerformed

    private void txtFatherNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFatherNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFatherNameActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void ckbFemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbFemaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckbFemaleActionPerformed

    private void ckbOtherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbOtherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckbOtherActionPerformed

    public void actionPerformed(ActionEvent ae) {
    String formno = "" + random;
    String name = txtName.getText();
    String fname = txtFatherName.getText();
    String dob = ((JTextField) jDateChooser1.getDateEditor().getUiComponent()).getText();
    String gender = null;
    if (ckbMale.isSelected()) {
        gender = "Male";
    } else if (ckbFemale.isSelected()) {
        gender = "Female";
    }

    String email = txtEmail.getText();
    String governorate = txtGovernorate.getText();

    String marital = null;
    if (ckbMarried.isSelected()) {
        marital = "Married";
    } else if (ckbUnmarried.isSelected()) {
        marital = "Single";
    } else if (ckbOther.isSelected()) {
        marital = "Other";
    }

    String pin = txtPin.getText();

    try {
        // التحقق من الحقول المطلوبة
        if (name.isEmpty() || fname.isEmpty() || email.isEmpty() || pin.isEmpty() ||
            governorate.isEmpty() || dob.isEmpty()) {
            throw new Exception("Please fill all required fields.");
        }

        if (gender == null) {
            throw new Exception("Please select the Gender.");
        }

        if (marital == null) {
            throw new Exception("Please select the Marital Status.");
        }

        // الاتصال بالداتا بيز
        Conn c = new Conn();

        
        String query = "INSERT INTO customers (form_no, full_name, father_name, date_of_birth, gender, email, " +
                       "marital_status, governorate, pin_code, account_type) " +
                       "VALUES ('"+formno+"','"+name+"','"+fname+"','"+dob+"','"+gender+"','"+email+"','"+
                       marital+"','"+governorate+"','"+pin+"','Saving Account')";

        c.s.executeUpdate(query);

        JOptionPane.showMessageDialog(this, "Data saved successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);

        
        SignUpPage2 nextPage = new SignUpPage2();
        //nextPage.setFormNo(formno); 
        nextPage.setVisible(true);
        this.dispose();

    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
}
    
    
    
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SignUpPage1().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNextToPage2;
    private javax.swing.JRadioButton ckbFemale;
    private javax.swing.JRadioButton ckbMale;
    private javax.swing.JRadioButton ckbMarried;
    private javax.swing.JRadioButton ckbOther;
    private javax.swing.JRadioButton ckbUnmarried;
    private javax.swing.ButtonGroup gbtnGender;
    private javax.swing.ButtonGroup gbtnMaritalStatues;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel lblApplicationFormNo;
    private javax.swing.JLabel lblDateOfBirth;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFatherName;
    private javax.swing.JLabel lblGavernorate;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblMaritalStatues;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPage1Personaldetails;
    private javax.swing.JLabel lblPin;
    private javax.swing.JPanel space;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFatherName;
    private javax.swing.JTextField txtGovernorate;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPin;
    // End of variables declaration//GEN-END:variables

    private static class buttonGroup {

        public buttonGroup() {
        }
    }
}
